name: Continuous Integration UI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - uses: actions/setup-node@v1 
        with:
          node-version: 12.x
      - name: Run tests
        run: |
          npm install
          npm run test
      - name: Test Event
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{secrets.ACCES_TOKEN}} #Use the access token created
          repository: OPOII/UITest #The repository to make the test
          event-type: npm run test:e2e:ui:headless 
          client-payload: '{"sha": "${{ github.sha }}"}'
